name: gendiff-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 8db7b649204b9099ea7aa6412e408f320ba95a26e9302de387a0d5f4c1d49ca7
        with:
          coverageCommand: make test-coverage
          debug: true
